dapps/reports/.eslintrc.json, dapps/reports/package.json, dapps/reports/public/cache/.gitignore, dapps/reports/src/components/Charts/Pie.tsx, dapps/reports/src/components/Filters/Menu.tsx, dapps/reports/src/pages/index.tsx, dapps/reports/src/services/classes/dataWarehouse.class.ts, dapps/reports/src/types/index.ts, dapps/reports/src/utils/serverSide.ts, dapps/reports/src/views/Homepage.tsx, dapps/reports/src/views/Welcome.tsx, dapps/reports/src/views/sections/FarmingFundsItems/TableFunds.tsx, dapps/reports/src/views/sections/FarmingFundsItems/TableResults.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionItems/Position.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailItems/TableWalletTokenDetail.tsx, dapps/reports/src/views/sections/TokenDetailItems/WalletTokenDetailContainer.tsx, dapps/reports/src/views/sections/TokenDetails.tsx, shared/config/constants.ts, shared/utils/mappers/index.ts, shared/utils/mappers/summary.ts, shared/utils/mappers/tokenDetails.tsx, types/additional.d.ts
- Add wallet
- Polish some stuff
=> feat: Add wallet

shared/utils/mappers/tokenDetails.tsx
- Add improvements to the cards
=> feat: Improve cards

dapps/reports/src/components/Charts/Waterfall.tsx, dapps/reports/src/components/Layout/Sidebar.tsx
=> fix: waterfall values

dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionContainer.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionItems/Card/Card.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionItems/CardList.tsx, shared/utils/mappers/tokenDetails.tsx, yarn.lock
- Apply new metrics
- Sort by total
- Improve token filters
=> feat: Apply new metrics to the token detail cards

dapps/reports/src/components/Layout/Header.tsx, dapps/reports/src/components/Layout/Layout.tsx, dapps/reports/src/components/Layout/Sidebar.tsx, dapps/reports/src/hooks/useIsLoading.tsx, dapps/reports/src/pages/_app.tsx, dapps/reports/src/views/sections/BalanceOverview.tsx, dapps/reports/src/views/sections/FarmingFunds.tsx, dapps/reports/src/views/sections/Hero.tsx, dapps/reports/src/views/sections/Summary.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionItems/Card/Card.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionItems/CardList.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailItems/TableTokenDetail.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailItems/TableWalletTokenDetail.tsx, dapps/reports/src/views/sections/TokenDetails.tsx, dapps/reports/src/views/sections/TreasuryVariation.tsx, shared/components/AnimatePresenceWrapper.tsx, shared/layout/Footer.tsx
- Add animations with framer motion
=> feat: add animations

.github/workflows/clean-up-pr-caches.yml, Dockerfile.reports.dev, README.md, dapps/reports/src/components/Layout/Layout.tsx, yarn.lock
=> feat: New docker for reports

dapps/reports/src/components/Charts/Waterfall.tsx
- improve tick count, interval and domain of the yAxis
=> feat: improve tick count, interval and domain of the yAxis

Dockerfile
=> refactor: dockerfile fix

dapps/reports/src/components/Layout/Sidebar.tsx, dapps/reports/src/views/sections/FarmingFundsItems/FundsContainer.tsx, dapps/reports/src/views/sections/FarmingFundsItems/TableFunds.tsx, dapps/reports/src/views/sections/FarmingFundsItems/TableResults.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailContainer.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailItems/TableTokenDetail.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailItems/TableWalletTokenDetail.tsx, dapps/reports/src/views/sections/TokenDetailItems/WalletTokenDetailContainer.tsx, shared/components/Form/YearAutocomplete.tsx, shared/components/PaperSection.tsx, shared/utils/index.ts
=> feat: feedback

dapps/reports/src/components/Charts/Pie.tsx, dapps/reports/src/views/sections/FarmingFundsItems/TableFunds.tsx, dapps/reports/src/views/sections/FarmingFundsItems/TableResults.tsx, dapps/reports/src/views/sections/Summary.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionItems/Card/Ratios.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailItems/TableTokenDetail.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailItems/TableWalletTokenDetail.tsx
- Improvement to the pie chart
- Add colspan to tables without pagination
- Order of element in special cards
=> feat: Improvement to the pie chart, tables and order in card

dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionItems/Card/Ratios.tsx
=> feat: improve card

Dockerfile
Dockerfile changes - docker image size is too large with current dockerfile!
=> refactor: dockerfile changes

Dockerfile
=> refactor: dockerfile minor fix

dapps/reports/src/components/Charts/Waterfall.tsx, dapps/reports/src/utils/math.ts, dapps/reports/src/views/sections/TreasuryVariation.tsx
- Improve waterfall chart
- Use config months 
Close #695 
=> feat: improve the proportion of columns in the waterfall chart

dapps/reports/src/views/sections/FarmingFundsItems/TableFunds.tsx
=> fix: Modify "includes" by "include"

dapps/reports/src/views/sections/TokenDetailItems/WalletTokenDetailContainer.tsx, shared/utils/mappers/summary.ts
Remove zero values
Close #699 
=> feat: In the pie charts, if a value lower than 0.00% is displayed, remove it

.github/workflows/workflow.yml
=> ci: changing CI to update the k8s deployment

dapps/reports/src/types/index.ts, dapps/reports/src/utils/serverSide.ts, dapps/reports/src/views/Homepage.tsx, dapps/reports/src/views/sections/TreasuryVariation.tsx, shared/utils/mappers/treasuryVariation.ts
=> feat: update metric to m08

dapps/reports/src/types/index.ts, dapps/reports/src/utils/serverSide.ts, dapps/reports/src/views/Homepage.tsx, dapps/reports/src/views/sections/Summary.tsx, dapps/reports/src/views/sections/TreasuryVariation.tsx, shared/utils/mappers/summary.ts
=> feat: Add global roi 

dapps/reports/src/views/sections/FarmingFundsItems/FundsContainer.tsx, dapps/reports/src/views/sections/Summary.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailContainer.tsx, dapps/reports/src/views/sections/TreasuryVariation.tsx, shared/components/InfoCard.tsx, shared/components/PaperSection.tsx
=> feat: Add more tooltips

dapps/reports/src/views/Homepage.tsx, dapps/reports/src/views/Welcome.tsx, dapps/reports/src/views/sections/FarmingFunds.tsx, dapps/reports/src/views/sections/FarmingFundsItems/FundsByProtocolContainer.tsx, dapps/reports/src/views/sections/FarmingFundsItems/FundsContainer.tsx, dapps/reports/src/views/sections/Summary.tsx, yarn.lock
- Let's add a text that indicates display from desktop
- The Farming Funds by Protocol chart that is in the Summary section, move it to Farming Funds section at the top. And put it in the same format as the wallet token detail chart but centered.
- The three pie charts in line
Close #742 
=> feat: Solve multiple feedback 

.github/workflows/workflow.yml
=> ci: fix ci run

dapps/reports/src/components/Share.tsx, shared/utils/mappers/treasuryVariation.ts
- When clicking on share, do not open the page in another window
- In the treasury variation section, there are two final balance columns
Close #759 
=> feat: Solve multiple feedback

dapps/reports/src/views/sections/TokenDetailItems/WalletTokenDetailContainer.tsx, shared/config/constants.ts, shared/utils/mappers/summary.ts, shared/utils/mappers/tokenDetails.tsx
Fix wallet detail filter
Close #761
=> fix: Wallet token detail filters 

dapps/reports/src/services/classes/dataWarehouse.class.ts, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionContainer.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionItems/Card/Card.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionItems/Card/Common.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionItems/Card/Ratios.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionItems/CardList.tsx, shared/utils/mappers/tokenDetails.tsx
Adjust information
Close #765 
=>  feat: adjust information in the vault cards

shared/config/constants.ts
Change Gnosis DAO name to Gnosis
Close #777
=> feat: change Gnosis DAO name to Gnosis

dapps/reports/DATA.md, dapps/reports/README.md, dapps/reports/src/pages/password-protect.tsx
=> feat: Add sections data readme

README.md, dapps/reports/DATA.md, dapps/reports/README.md, dapps/reports/src/services/classes/dataWarehouse.class.ts
=> feat: update readme

shared/utils/mappers/tokenDetails.tsx
- Fix total usd by card
Close #784
=> feat: check summary of the items in the card

dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionItems/Card/Common.tsx, shared/utils/mappers/tokenDetails.tsx
- Update some texts
Close #786
=> feat: Change texts

dapps/reports/src/components/Charts/Pie.tsx, dapps/reports/src/views/sections/Summary.tsx, shared/components/InfoCard.tsx
=> feat: Improve pie chart

dapps/panic-button/package.json, dapps/reports/package.json, dapps/reports/src/components/Charts/Pie.tsx, dapps/reports/src/views/sections/Summary.tsx, shared/components/InfoCard.tsx, shared/package.json
=> Release 0.1.0

.github/workflows/workflow.yml
=> ci: docker tag fix

.github/workflows/workflow.yml
Reverts KarpatkeyDAO/karpatkey-dapps-monorepo#804
=> Revert "ci: docker tag fix"

dapps/reports/src/components/Charts/Waterfall.tsx, dapps/reports/src/utils/math.ts, yarn.lock
=> feat: Improve waterfall

dapps/reports/src/components/Charts/Waterfall.tsx, shared/config/theme.tsx
=> feat: add fontSize

dapps/reports/src/utils/format.ts, dapps/reports/src/views/sections/FarmingFundsItems/TableResults.tsx, shared/utils/mappers/farmingFunds.tsx
=> feat: remove zero values

.github/workflows/workflow.yml
=> ci: deployment fix

dapps/reports/src/views/sections/Summary.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionItems/Card/Ratios.tsx, shared/utils/mappers/tokenDetails.tsx, yarn.lock
Just modify some texts
Close #863 
=> feat: Update texts

dapps/reports/src/components/Layout/Layout.tsx, dapps/reports/src/views/sections/TokenDetailItems/WalletTokenDetailContainer.tsx, shared/layout/Footer.tsx
=> feat: Add disclaimer and fix justify content

dapps/reports/src/views/sections/FarmingFunds.tsx
=> feat: Hide table "Farming results detail by position"

dapps/reports/src/config/constants.ts, dapps/reports/src/views/sections/FarmingFundsItems/TableFunds.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionItems/Card/Card.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionItems/Card/Position.tsx, shared/components/UniswapHelpText.tsx
Add tooltip to the uniswapV3 positions
Close #870 
=> feat: Add tooltip to the uniswapV3 positions

dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionContainer.tsx, shared/utils/mappers/tokenDetails.tsx, yarn.lock
Use Type, change CDP and Standard card logic
Close #862 
=> feat: Use Type, change CDP and Standard card logic

dapps/reports/src/components/Layout/Sidebar.tsx
=> feat: Solve render route problem

dapps/reports/next.config.js, dapps/reports/package.json, dapps/reports/src/components/Layout/Layout.tsx, shared/layout/Footer.tsx
=> feat: Add version release

dapps/reports/src/components/Filters/Menu.tsx, dapps/reports/src/components/Layout/Layout.tsx, shared/components/CustomPopover.tsx, shared/components/Filter/Filter.tsx
=> feat: Add ref

shared/components/Form/MonthAutocomplete.tsx
=> feat: add month check

dapps/reports/src/views/sections/FarmingFundsItems/FundsByProtocolContainer.tsx
Modify tooltip text
Close #990 
=> feat: modify tooltip

shared/components/Form/MonthAutocomplete.tsx
=> feat: add august

.github/workflows/workflow.yml, dapps/panic-button/package.json, dapps/reports/package.json, shared/components/Form/MonthAutocomplete.tsx, shared/package.json
=> Release v0.2.14

dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionItems/CardList.tsx
=> feat: fix template

dapps/reports/src/utils/format.ts, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailItems/TableTokenDetail.tsx
Downward arrow when no price variation
=> feat: Downward arrow when no price variation

dapps/reports/src/views/sections/TokenDetailItems/TokenDetailItems/TableTokenDetail.tsx
=> feat: reduce size of the icons

dapps/reports/src/views/sections/FarmingFunds.tsx
=> feat: update text for farming results swaps

dapps/reports/src/views/sections/BalanceOverviewItems/TableBlockchain.tsx, dapps/reports/src/views/sections/BalanceOverviewItems/TableType.tsx, dapps/reports/src/views/sections/FarmingFundsItems/TableFunds.tsx, dapps/reports/src/views/sections/FarmingFundsItems/TableResults.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailItems/TableTokenDetail.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailItems/TableWalletTokenDetail.tsx
Remove excessive row when no ‘View more’
=> feat: Excessive row when no ‘View more’

shared/utils/mappers/tokenDetails.tsx
Now we include the negative values
=> feat: Token details fix

dapps/reports/src/components/Layout/Header.tsx, dapps/reports/src/components/Layout/Layout.tsx, dapps/reports/src/components/Loading.tsx, dapps/reports/src/pages/_app.tsx, dapps/reports/src/pages/index.tsx, dapps/reports/src/utils/serverSide.ts, dapps/reports/src/views/Dashboard.tsx, dapps/reports/src/views/sections/Dashboard/NumberBlock.tsx
Solve feedback for new homepage dashboard
=> feat : feedback homepage

dapps/reports/src/types/index.ts, dapps/reports/src/utils/serverSide.ts, dapps/reports/src/views/Dashboard.tsx, dapps/reports/src/views/sections/Dashboard/NumberBlock.tsx, dapps/reports/src/views/sections/Dashboard/Title.tsx, dapps/reports/src/views/sections/Dashboard/Value.tsx
=> feat: homepage feedback

dapps/reports/src/views/Dashboard.tsx
Update dashboard with some feedback
=> feat: update dashboard

dapps/reports/src/views/Dashboard.tsx
- Apply value font to title
- Remove text
- Add tooltip to table rows
=> feat: dashboard feedback

dapps/reports/src/components/Layout/HomepageFooter.tsx, dapps/reports/src/components/Layout/HomepageHeader.tsx, dapps/reports/src/components/Layout/Layout.tsx, dapps/reports/src/components/LogoKarpatkey.tsx, dapps/reports/src/hooks/useScrollDirection.tsx, dapps/reports/src/views/Dashboard.tsx
- Improve header, layour and footer
=> feat: add improvement to the homepage layout

dapps/reports/src/components/Layout/Layout.tsx, dapps/reports/src/pages/404.tsx, dapps/reports/src/pages/500.tsx, dapps/reports/src/pages/index.tsx, dapps/reports/src/utils/serverSide.ts, dapps/reports/src/views/Dashboard.tsx, shared/components/Form/DAOAutocomplete.tsx, shared/config/constants.ts
=> feat: Disable/Remove Lido

dapps/reports/src/components/LinkWrapper.tsx, dapps/reports/src/components/LogoKarpatkey.tsx, dapps/reports/src/views/Dashboard.tsx
=> feat: add Link Custom to wrap table rows and other components

shared/config/constants.ts
=> feat: Update CoW to CoW Protocol

dapps/reports/src/components/Layout/Homepage/Footer.tsx, dapps/reports/src/components/Layout/Homepage/Header.tsx, dapps/reports/src/components/Layout/Layout.tsx, dapps/reports/src/hooks/useScreenSize.tsx, dapps/reports/src/views/Dashboard.tsx, dapps/reports/src/views/sections/Dashboard/NumberBlock.tsx
- Define a min screen layout for homepage
=> feat: Define a min screen layout for homepage

shared/config/constants.ts
=> feat: add september report

dapps/reports/src/views/sections/FarmingFunds.tsx
Fix farming results
No issue result
=> hotfix: Fix farming results

shared/config/constants.ts
=> feat: remove september

dapps/reports/package.json
=> feat: bump Dependencies

shared/utils/mappers/tokenDetails.tsx
=> fix: Wallet token detail ungrouped tokens

dapps/reports/src/components/Layout/Layout.tsx
=> feat: header check

dapps/reports/src/components/Layout/Homepage/Footer.tsx
=> fix: firefox footer

dapps/reports/src/components/Layout/Homepage/Footer.tsx, shared/layout/Footer.tsx
=> feat: Update github link

shared/utils/mappers/treasuryVariation.ts
Remove 0 column from the Treasury variation for the period (detail) chart
=> feat: Remove 0 column from the Treasury variation for the period (detail) chart

dapps/reports/src/views/Dashboard.tsx
=> feat: update title in the dashboard

dapps/reports/src/views/Dashboard.tsx
=> feat: update total funds title

dapps/reports/src/views/Dashboard.tsx
Remove title from the homepage
=> hotfix: remove title

dapps/reports/src/components/Layout/Layout.tsx, dapps/reports/src/views/Dashboard.tsx
=> feat: move text

dapps/reports/src/components/Layout/Homepage/Footer.tsx, dapps/reports/src/views/Dashboard.tsx, dapps/reports/src/views/sections/Dashboard/NumberBlock.tsx, dapps/reports/src/views/sections/Dashboard/Value.tsx
=> Hotfix: move title

dapps/reports/src/views/Dashboard.tsx
=> Hotfix: feedback move title

dapps/reports/src/views/Dashboard.tsx
=> feat: remove title

dapps/reports/src/views/Dashboard.tsx
=> feat: feedback, move text more to the top

dapps/reports/src/views/Dashboard.tsx
=> feat: move title

shared/utils/mappers/treasuryVariation.ts
=> hotfix: remove zero column

dapps/reports/src/views/Dashboard.tsx, dapps/reports/src/views/Homepage.tsx, dapps/reports/src/views/sections/Summary.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionItems/Card/ProtocolIcon.tsx
=> hotfix: ens apy main

shared/components/ErrorBoundary/ErrorBoundary.tsx, shared/config/constants.ts
=> hotfix: November report

dapps/reports/DATA.md, dapps/reports/src/services/classes/dataWarehouse.class.ts, shared/components/ErrorBoundary/ErrorBoundary.tsx
=> hotfix: update view data

shared/components/ErrorBoundary/ErrorBoundary.tsx, shared/config/constants.ts
=> feat: add november report to main

shared/config/constants.ts
=> hotfix: rollback november

dapps/reports/src/views/sections/Summary.tsx
=> feat: add ens apy

shared/config/constants.ts
=> feat: add november

dapps/reports/src/utils/serverSide.ts, dapps/reports/src/views/sections/FarmingFundsItems/OperationsContainer.tsx, shared/utils/mappers/summary.ts
=> feat: fix DeFi funds in the homepage

dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionContainer.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionItems/Card/Card.tsx, shared/components/Filter/Filter.tsx, shared/components/Filter/Form.tsx, shared/components/Form/DeFiTypeAutocomplete.tsx, shared/utils/mappers/tokenDetails.tsx
=> feat: add card feature

dapps/reports/src/config/constants.ts, shared/utils/mappers/balanceOverview.ts, shared/utils/mappers/summary.ts
=> feat: add checks and force prod

dapps/reports/src/config/constants.ts, shared/utils/mappers/balanceOverview.ts, shared/utils/mappers/farmingFunds.tsx, shared/utils/mappers/summary.ts
=> Release v0.2.22

dapps/reports/src/views/sections/Hero.tsx, shared/utils/index.ts
=> hotfix: re-render image

dapps/reports/src/views/sections/TokenDetailItems/TokenDetailItems/TableWalletTokenDetail.tsx
=> hotfix: Update title

dapps/reports/src/components/Filters/Menu.tsx, dapps/reports/src/pages/index.tsx, dapps/reports/src/utils/serverSide.ts, shared/components/Form/MonthAutocomplete.tsx, shared/components/Form/YearAutocomplete.tsx, shared/config/constants.ts, shared/utils/index.ts
=> hotfix: fix year month problem

dapps/reports/src/components/Filters/Menu.tsx, dapps/reports/src/pages/index.tsx, dapps/reports/src/utils/serverSide.ts, shared/components/Form/MonthAutocomplete.tsx, shared/components/Form/YearAutocomplete.tsx, shared/config/constants.ts, shared/utils/index.ts
=> hotfix: fix year month problem in the main branch

dapps/reports/src/config/constants.ts
=> hotfix: modify constant

dapps/reports/src/config/constants.ts
=> hotfix: rollback constant

dapps/reports/src/types/index.ts, dapps/reports/src/utils/serverSide.ts, dapps/reports/src/views/Dashboard.tsx
=> hotfix: fix APY

shared/config/constants.ts
=> feat: add december month

shared/config/constants.ts
=> feat: add december in the main branch

dapps/reports/src/utils/serverSide.ts, shared/utils/mappers/summary.ts, shared/utils/mappers/treasuryVariation.ts, yarn.lock
=> fix: defi funds problem in the main branch

dapps/reports/src/views/sections/TokenDetailItems/TokenDetailItems/TableWalletTokenDetail.tsx
=> hotfix: update title in the main branch

shared/layout/Footer.tsx
=> hotfix: Update year in the footer

dapps/reports/src/components/Layout/Homepage/Footer.tsx
=> hotfix: add proper year to the footer

dapps/reports/src/components/Layout/Homepage/Footer.tsx, shared/layout/Footer.tsx
=> hotfix: add proper year to the footer in the main branch

dapps/reports/src/pages/api/cache.ts
=> feat: remove

dapps/reports/src/services/classes/dataWarehouse.class.ts, dapps/reports/src/views/Dashboard.tsx, dapps/reports/src/views/sections/Dashboard/Value.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionItems/Card/Card.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionItems/Card/Common.tsx, dapps/reports/src/views/sections/TokenDetailItems/TokenDetailByPositionItems/Card/Ratios.tsx, shared/utils/mappers/balanceOverview.ts, shared/utils/mappers/summary.ts, shared/utils/mappers/tokenDetails.tsx, shared/utils/mappers/treasuryVariation.ts
=> feat: add switch support for cards

dapps/reports/src/scripts/generateReports.ts, dapps/reports/src/services/classes/dataWarehouse.class.ts, dapps/reports/src/views/sections/TokenDetails.tsx, shared/utils/mappers/tokenDetails.tsx
=> feat: fix problem with price average

.github/workflows/docker.yml
=> ci: add devprod

dapps/reports/src/components/Filters/Menu.tsx, dapps/reports/src/utils/params.ts
=> feat: improve function

dapps/reports/src/scripts/generateReports.ts, dapps/reports/src/utils/params.ts, shared/utils/mappers/tokenDetails.tsx
=> hotfix: prices

shared/config/constants.ts
=> feat: update lido config

dapps/reports/src/views/Dashboard.tsx, shared/config/constants.ts
=> feat: fix title and disable Aave

dapps/reports/src/views/sections/FarmingFundsItems/TableFunds.tsx, dapps/reports/src/views/sections/FarmingFundsItems/TableOperations.tsx
=> feat: add decimals to some columns

shared/utils/mappers/summary.ts
=> feat: update property

dapps/reports/src/components/Filters/Menu.tsx, shared/components/Filter/Filter.tsx, shared/components/Filter/Form.tsx, shared/components/Form/YearMonthAutocomplete.tsx
=> feat: improve filtering on dev

shared/config/constants.ts
=> feat: add january report

shared/config/constants.ts
=> feat: enable aave

dapps/reports/src/middleware.ts
=> feat: use constant

shared/utils/mappers/tokenDetails.tsx
=> feat: add support for unclaimed rewards in cdp cards

dapps/reports/src/components/Charts/NewPie.tsx, dapps/reports/src/views/sections/FarmingFundsItems/FundsByProtocolContainer.tsx, dapps/reports/src/views/sections/Summary.tsx, dapps/reports/src/views/sections/TokenDetailItems/WalletTokenDetailContainer.tsx, shared/config/theme.tsx, shared/utils/mappers/tokenDetails.tsx
=> Release v0.2.24

dapps/reports/src/components/Layout/Homepage/Header.tsx, dapps/reports/src/hooks/useScrollDirection.tsx, dapps/reports/src/pages/index.tsx, dapps/reports/src/views/Dashboard.tsx, dapps/reports/src/views/sections/Dashboard/Card.tsx, dapps/reports/src/views/sections/Dashboard/NumberBlockCard.tsx, dapps/reports/src/views/sections/Dashboard/Table.tsx, dapps/reports/src/views/sections/Dashboard/Value.tsx, shared/config/theme.tsx
=> feat: improve mobile version of dashboard

dapps/reports/src/components/Layout/Homepage/Header.tsx
=> feat: add animation to the menu

dapps/reports/src/views/Dashboard.tsx, dapps/reports/src/views/sections/Dashboard/NumberBlock.tsx
=> feat: feedback high res

deployment-template.yaml
=> fix: change some parameters in deployment template

dapps/reports/src/middleware.ts
=> fix: password protect

dapps/reports/src/components/LinkWrapper.tsx, dapps/reports/src/views/sections/Dashboard/Card.tsx, dapps/reports/src/views/sections/Dashboard/NumberBlockCard.tsx
=> feat: add improvements to the mobile version

dapps/reports/src/components/Layout/Homepage/Footer.tsx
=> feat: improve footer

shared/config/constants.ts
=> feat: add february

dapps/reports/package.json, dapps/reports/public/images/protocols/binance.svg, dapps/reports/src/views/sections/Hero.tsx, shared/config/constants.ts, yarn.lock
=> feat: add new addresses

src/pages/index.tsx, src/scripts/generateDashboard.ts
=> fix: redirect with new parameters

src/views/sections/report/farmingFundsItems/TableFunds.tsx, src/views/sections/report/farmingFundsItems/TableOperations.tsx, src/views/sections/report/tokenDetailItems/TableTokenDetail.tsx
=> feat: improve tables

src/components/Carousel.tsx, src/components/filters/mobile/FilterContent.tsx, src/styles/globals.css, src/views/sections/report/farmingFundsItems/FundsContainer.tsx, src/views/sections/report/farmingFundsItems/OperationsContainer.tsx, src/views/sections/report/farmingFundsItems/ResultsContainer.tsx, src/views/sections/report/tokenDetailItems/CardList.tsx, src/views/sections/report/tokenDetailItems/TokenDetailByPositionContainer.tsx, src/views/sections/report/tokenDetailItems/TokenDetailContainer.tsx, src/views/sections/report/tokenDetailItems/WalletTokenDetailContainer.tsx, src/views/sections/report/tokenDetailItems/card/desktop/Card.tsx, src/views/sections/report/tokenDetailItems/card/desktop/Common.tsx, src/views/sections/report/tokenDetailItems/card/desktop/ItemText.tsx, src/views/sections/report/tokenDetailItems/card/desktop/ItemUSD.tsx, src/views/sections/report/tokenDetailItems/card/desktop/Position.tsx, src/views/sections/report/tokenDetailItems/card/desktop/ProtocolIcon.tsx, src/views/sections/report/tokenDetailItems/card/desktop/Ratios.tsx, src/views/sections/report/tokenDetailItems/card/desktop/Title.tsx, src/views/sections/report/tokenDetailItems/card/mobile/Card.tsx, src/views/sections/report/tokenDetailItems/card/mobile/Common.tsx, src/views/sections/report/tokenDetailItems/card/mobile/ItemText.tsx, src/views/sections/report/tokenDetailItems/card/mobile/ItemUSD.tsx, src/views/sections/report/tokenDetailItems/card/mobile/Position.tsx, src/views/sections/report/tokenDetailItems/card/mobile/ProtocolIcon.tsx, src/views/sections/report/tokenDetailItems/card/mobile/Ratios.tsx, src/views/sections/report/tokenDetailItems/card/mobile/Title.tsx
=> feat: Improve mobile version, feedback

src/components/filters/mobile/Menu.tsx, src/views/sections/report/Summary.tsx
=> fix: use short version of the month, animation and fix share button

src/components/charts/Waterfall.tsx, src/views/sections/report/Summary.tsx
=> fix: display full names in the waterfall chart

src/views/sections/report/Hero.tsx, src/views/sections/report/balanceOverviewItems/TableBlockchain.tsx, src/views/sections/report/balanceOverviewItems/TableType.tsx, src/views/sections/report/balanceOverviewItems/TableTypeDDay.tsx, src/views/sections/report/farmingFundsItems/TableFunds.tsx, src/views/sections/report/farmingFundsItems/TableOperations.tsx, src/views/sections/report/farmingFundsItems/TableResults.tsx, src/views/sections/report/tokenDetailItems/TableTokenDetail.tsx, src/views/sections/report/tokenDetailItems/TableWalletTokenDetail.tsx
=> fix: add fixed column to some tables

src/components/charts/NewPie.tsx, src/styles/globals.css, src/views/sections/report/balanceOverviewItems/TableTypeDDay.tsx, src/views/sections/report/farmingFundsItems/TableFunds.tsx, src/views/sections/report/farmingFundsItems/TableOperations.tsx, src/views/sections/report/tokenDetailItems/TableTokenDetail.tsx
…al, fix header, remove weight
=> fix: disable selection of slice in the pie chart, and other stuff

src/components/layout/report/desktop/BodyWrapper.tsx, src/styles/globals.css, src/views/sections/report/farmingFundsItems/TableFunds.tsx, src/views/sections/report/farmingFundsItems/TableOperations.tsx, src/views/sections/report/tokenDetailItems/TableTokenDetail.tsx
=> feat: improve share column in the table "token detail with price variation"

src/components/layout/report/desktop/Wrapper.tsx, src/styles/globals.css
=> fix: issue with overflow

src/components/filters/Menu.tsx, src/components/layout/Layout.tsx, src/components/layout/report/desktop/Body.tsx, src/components/layout/report/desktop/BodyWrapper.tsx, src/components/layout/report/mobile/Wrapper.tsx, src/pages/index.tsx, src/styles/globals.css, src/views/Report.tsx
=> feat: add improvement to the routing

src/config/constants.ts
=> feat: add march report

src/config/constants.ts, src/views/sections/report/farmingFundsItems/TableFunds.tsx, src/views/sections/report/farmingFundsItems/TableOperations.tsx, src/views/sections/report/tokenDetailItems/TableTokenDetail.tsx, src/views/sections/report/tokenDetailItems/TableWalletTokenDetail.tsx
=> feat: add bold

src/components/charts/Waterfall.tsx, src/components/layout/Layout.tsx, src/components/layout/dashboard/Wrapper.tsx, src/scripts/generateDashboard.ts, src/utils/index.ts, src/views/sections/report/TreasuryVariation.tsx, src/views/sections/report/tokenDetailItems/CardList.tsx, src/views/sections/report/tokenDetailItems/TableTokenDetail.tsx, src/views/sections/report/tokenDetailItems/TableWalletTokenDetail.tsx, src/views/sections/report/tokenDetailItems/WalletTokenDetailContainer.tsx
- Last month displayed in the dashboard
- Waterfall bottom
- Layout scroll
- Cards height
=> fix: last month displayed in the dashboard

src/components/charts/NewPie.tsx, src/components/layout/report/desktop/Footer.tsx, src/pages/index.tsx, src/styles/globals.css, src/views/sections/report/Hero.tsx, src/views/sections/report/Summary.tsx, src/views/sections/report/tokenDetailItems/TableTokenDetail.tsx
=> feat: Lido redirect and issue with highcharts

src/components/InfoCard.tsx, src/components/PaperSection.tsx, src/components/UniswapHelpText.tsx, src/components/filters/Filter.tsx, src/components/filters/mobile/FilterContent.tsx, src/views/Dashboard.tsx, src/views/sections/dashboard/Card.tsx, src/views/sections/dashboard/Table.tsx, src/views/sections/report/TreasuryVariation.tsx, src/views/sections/report/balanceOverviewItems/TableTypeDDay.tsx, src/views/sections/report/farmingFundsItems/TableFunds.tsx, src/views/sections/report/farmingFundsItems/TableOperations.tsx, src/views/sections/report/tokenDetailItems/TableTokenDetail.tsx
=> feat: Add month and year in card, improve tooltip, wording

src/components/filters/mobile/FilterContent.tsx, src/components/filters/mobile/Menu.tsx
=> feat: add filters applied, remove report filter icon

src/components/ButtonAddress.tsx, src/components/carousels/addresses.tsx, src/components/carousels/pieCharts.tsx, src/components/charts/NewPie.tsx, src/styles/globals.css, src/views/sections/report/Hero.tsx, src/views/sections/report/Summary.tsx, src/views/sections/report/farmingFundsItems/FundsByProtocolContainer.tsx, src/views/sections/report/tokenDetailItems/WalletTokenDetailContainer.tsx
=> feat: Improve carousel

src/components/filters/mobile/FilterContent.tsx, src/components/filters/mobile/Menu.tsx, src/views/sections/report/Summary.tsx, src/views/sections/report/balanceOverviewItems/TableBlockchain.tsx, src/views/sections/report/balanceOverviewItems/TableType.tsx, src/views/sections/report/balanceOverviewItems/TableTypeDDay.tsx, src/views/sections/report/farmingFundsItems/FundsByProtocolContainer.tsx, src/views/sections/report/farmingFundsItems/TableFunds.tsx, src/views/sections/report/farmingFundsItems/TableOperations.tsx, src/views/sections/report/farmingFundsItems/TableResults.tsx, src/views/sections/report/tokenDetailItems/TableTokenDetail.tsx, src/views/sections/report/tokenDetailItems/TableWalletTokenDetail.tsx
=> fix: border in tables, improve piechart, wording

src/components/ButtonAddress.tsx, src/components/charts/NewPie.tsx, src/styles/globals.css, src/views/sections/report/Hero.tsx, src/views/sections/report/Summary.tsx, src/views/sections/report/farmingFundsItems/FundsByProtocolContainer.tsx
=> feat: remove unused key II

src/config/constants.ts
=> feat: add march report for aave

src/components/layout/Layout.tsx, src/pages/index.tsx
=> fix: add default to currency

src/components/layout/Layout.tsx, src/config/constants.ts, src/pages/index.tsx
=> Release v0.2.28

src/components/Share.tsx, src/components/filters/Menu.tsx
=> fix: use state in the shared button

src/components/carousels/cards.tsx, src/views/sections/report/tokenDetailItems/CardList.tsx, src/views/sections/report/tokenDetailItems/card/mobile/Card.tsx
=> feat: feedback cards mobile

src/components/carousels/cards.tsx, src/views/sections/report/tokenDetailItems/CardList.tsx
=> feat: add badge with numbers

src/components/layout/Common.tsx, src/components/layout/dashboard/Header.tsx, src/components/layout/dashboard/Wrapper.tsx, src/styles/globals.css, src/views/Dashboard.tsx
=> fix: header and remove text

src/components/carousels/cards.tsx
=> feat: reduce dot size

src/components/carousels/cards.tsx, src/views/sections/report/tokenDetailItems/CardList.tsx, src/views/sections/report/tokenDetailItems/card/mobile/Card.tsx
=> feat: add improvements to the cards carousel

src/views/sections/report/tokenDetailItems/card/mobile/Card.tsx
=> feat: display arrows if the scrollbar is visible

src/components/carousels/cards.tsx, src/views/sections/report/tokenDetailItems/CardList.tsx, src/views/sections/report/tokenDetailItems/card/mobile/Card.tsx
=> feat: use seven dots instead of five, and fix a problem when displaying only one card in the carousel

src/components/carousels/addresses.tsx, src/views/sections/report/Hero.tsx
=> feat: apply dots to the addresses

src/components/carousels/pieCharts.tsx, src/views/sections/report/Summary.tsx
=> feat: add custom dots to pie charts

src/styles/globals.css
=> fix: scroll

src/config/constants.ts
=> feat: add april month

src/config/constants.ts
=> feat: add new addresses to CoW and Aave

src/components/charts/NewPie.tsx, src/styles/globals.css, src/views/sections/report/farmingFundsItems/FundsByProtocolContainer.tsx, src/views/sections/report/tokenDetailItems/WalletTokenDetailContainer.tsx
=> fix: overflow in some components

src/components/filters/mobile/FilterContent.tsx
=> feat: improve filters

src/components/charts/NewPie.tsx, src/styles/globals.css, src/views/sections/report/Summary.tsx
=> fix: labels in the pie chart

src/views/sections/report/Summary.tsx
=> fix: reduce size

src/components/charts/NewPie.tsx, src/components/filters/mobile/FilterContent.tsx, src/styles/globals.css, src/views/sections/report/Summary.tsx
=> Release v0.2.33

src/styles/globals.css, src/views/sections/report/BalanceOverview.tsx, src/views/sections/report/TreasuryVariation.tsx, src/views/sections/report/balanceOverviewItems/TableBlockchain.tsx, src/views/sections/report/balanceOverviewItems/TableType.tsx
Change animation arrow
Improve toggle
Adjust column width to be used in the arrow left property
=> feat: change animation arrow

src/views/sections/report/balanceOverviewItems/TableType.tsx, src/views/sections/report/balanceOverviewItems/TableTypeDDay.tsx
=> feat: add navigation arrows to table type

src/views/sections/report/balanceOverviewItems/TableBlockchain.tsx, src/views/sections/report/balanceOverviewItems/TableType.tsx, src/views/sections/report/balanceOverviewItems/TableTypeDDay.tsx
=> feat: add adjustment

.github/workflows/merge-dependabot.yml
=> feat: update dependabot

.github/dependabot.yml
=> feat: update workflow

src/utils/index.ts
=> feat: remove unused code

src/components/PaperSection.tsx, src/components/layout/Layout.tsx, src/contexts/state.ts, src/styles/globals.css, src/views/Dashboard.tsx, src/views/sections/dashboard/Card.tsx, src/views/sections/report/Hero.tsx, src/views/sections/report/Summary.tsx
=> fix: position of the blocks 

src/components/GoogleAnalytics.tsx, src/utils/index.ts
=> feat: add methods to check the domains

src/components/layout/Common.tsx, src/views/sections/report/balanceOverviewItems/TableBlockchain.tsx, src/views/sections/report/balanceOverviewItems/TableType.tsx, src/views/sections/report/balanceOverviewItems/TableTypeDDay.tsx, src/views/sections/report/farmingFundsItems/TableFunds.tsx, src/views/sections/report/farmingFundsItems/TableOperations.tsx, src/views/sections/report/tokenDetailItems/CardList.tsx, src/views/sections/report/tokenDetailItems/TableTokenDetail.tsx, src/views/sections/report/tokenDetailItems/TableWalletTokenDetail.tsx
=> feat: Add scroll and arrows to the tables

src/views/sections/report/tokenDetailItems/TableTokenDetail.tsx
=> feat: fix table

src/views/sections/report/farmingFundsItems/TableOperations.tsx
=> fix: Operations table first column width

src/components/CustomPopover.tsx
=> fix: filter height

src/config/constants.ts
=> feat: add may

src/config/constants.ts
=> feat: improve short blockchain name for safe

src/components/filters/Menu.tsx, src/components/layout/report/Disclaimer.tsx, src/components/layout/report/desktop/Header.tsx, src/components/layout/report/desktop/Sidebar.tsx, src/components/layout/report/mobile/Header.tsx, src/utils/mappers/balanceOverview.ts, src/utils/mappers/farmingFunds.tsx, src/utils/mappers/summary.ts, src/utils/mappers/tokenDetails.tsx, src/utils/mappers/treasuryVariation.ts, src/utils/params.ts, src/views/sections/dashboard/Card.tsx, src/views/sections/dashboard/Table.tsx, src/views/sections/report/BalanceOverview.tsx, src/views/sections/report/FarmingFunds.tsx, src/views/sections/report/Summary.tsx, src/views/sections/report/TreasuryVariation.tsx, src/views/sections/report/farmingFundsItems/FundsByProtocolContainer.tsx, src/views/sections/report/farmingFundsItems/FundsContainer.tsx, src/views/sections/report/farmingFundsItems/TableFunds.tsx, src/views/sections/report/tokenDetailItems/TableTokenDetail.tsx, src/views/sections/report/tokenDetailItems/TokenDetailByPositionContainer.tsx, src/views/sections/report/tokenDetailItems/card/desktop/Card.tsx, src/views/sections/report/tokenDetailItems/card/mobile/Card.tsx
=> feat: hide APY

package.json, src/components/filters/Menu.tsx, src/components/layout/report/Disclaimer.tsx, src/components/layout/report/desktop/Header.tsx, src/components/layout/report/desktop/Sidebar.tsx, src/components/layout/report/mobile/Header.tsx, src/utils/mappers/balanceOverview.ts, src/utils/mappers/farmingFunds.tsx, src/utils/mappers/summary.ts, src/utils/mappers/tokenDetails.tsx, src/utils/mappers/treasuryVariation.ts, src/utils/params.ts, src/views/sections/dashboard/Card.tsx, src/views/sections/dashboard/Table.tsx, src/views/sections/report/BalanceOverview.tsx, src/views/sections/report/FarmingFunds.tsx, src/views/sections/report/Summary.tsx, src/views/sections/report/TreasuryVariation.tsx, src/views/sections/report/farmingFundsItems/FundsByProtocolContainer.tsx, src/views/sections/report/farmingFundsItems/FundsContainer.tsx, src/views/sections/report/farmingFundsItems/TableFunds.tsx, src/views/sections/report/tokenDetailItems/TableTokenDetail.tsx, src/views/sections/report/tokenDetailItems/TokenDetailByPositionContainer.tsx, src/views/sections/report/tokenDetailItems/card/desktop/Card.tsx, src/views/sections/report/tokenDetailItems/card/mobile/Card.tsx, yarn.lock
=> Release v0.2.41

src/views/sections/dashboard/Card.tsx
=> feat: Update date format

src/components/charts/Waterfall.tsx, src/services/classes/dataWarehouse.class.ts, src/utils/mappers/farmingFunds.tsx, src/utils/mappers/summary.ts, src/utils/mappers/treasuryVariation.ts, src/views/sections/report/TreasuryVariation.tsx
=> feat: Treasury variant graph adjustment

src/utils/mappers/farmingFunds.tsx, src/utils/mappers/summary.ts
=> feat: add check for defi results

src/components/filters/mobile/Menu.tsx
=> feat: update logos

src/components/filters/mobile/Menu.tsx
=> feat: update logo

src/components/filters/mobile/Menu.tsx
=> feat: improve logos

src/components/charts/Waterfall.tsx, src/utils/format.ts, src/utils/mappers/treasuryVariation.ts, src/views/sections/report/tokenDetailItems/card/ProtocolIcon.tsx
=> feat: fix eth currency and lido logo
